# Generated by Django 4.2.4 on 2023-08-30 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='constcred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('const_id', models.CharField(max_length=50)),
                ('const_name', models.CharField(max_length=50)),
                ('const_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='distrcred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distr_id', models.CharField(max_length=50)),
                ('dist_name', models.CharField(max_length=50)),
                ('distr_pass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExcelFileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file_upload', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_no', models.IntegerField()),
                ('booth_name', models.CharField(max_length=40)),
                ('par_consistuency', models.CharField(max_length=50)),
                ('total_votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='voterinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('distno', models.IntegerField()),
                ('distname', models.CharField(max_length=50)),
                ('ac_no', models.IntegerField()),
                ('ac_name', models.CharField(max_length=50)),
                ('part_n0', models.IntegerField()),
                ('part_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='votercred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voterid', models.CharField(max_length=50)),
                ('voterpass', models.CharField(max_length=50)),
                ('constituency', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tofassignment1.constcred')),
            ],
        ),
        migrations.AddField(
            model_name='constcred',
            name='district',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tofassignment1.distrcred'),
        ),
    ]
